blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/andrestobelem/de/discussions
    about: Use Discussions for questions that are not yet actionable issues.
